"""add ocr attempt count to receipt images

Revision ID: 10aa10a409ab
Revises: 3407491ef180
Create Date: 2026-08-15 12:32:41.282680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10aa10a409ab'
down_revision: Union[str, None] = '3407491ef180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_images', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('ocr_attempt_count', sa.Integer(), nullable=False, server_default='0')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_images', schema=None) as batch_op:
        batch_op.drop_column('ocr_attempt_count')
    # ### end Alembic commands ###
